// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoEhABLIbuDZyk8M5EM_ITqsNHbJj18os',
    appId: '1:802294275670:web:2fb5635589903973e5a5f7',
    messagingSenderId: '802294275670',
    projectId: 'notz-6b2b2',
    authDomain: 'notz-6b2b2.firebaseapp.com',
    storageBucket: 'notz-6b2b2.appspot.com',
    measurementId: 'G-XG4ZRHSJZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49524AYZh9_-1IXgJvCHQKiRv-5u0ce0',
    appId: '1:802294275670:android:03d84359c2cc15a6e5a5f7',
    messagingSenderId: '802294275670',
    projectId: 'notz-6b2b2',
    storageBucket: 'notz-6b2b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA22aaAinf7g335FLXdIEGguBQmpt_4lsE',
    appId: '1:802294275670:ios:fe48b597ba46c15ae5a5f7',
    messagingSenderId: '802294275670',
    projectId: 'notz-6b2b2',
    storageBucket: 'notz-6b2b2.appspot.com',
    iosBundleId: 'com.example.notz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA22aaAinf7g335FLXdIEGguBQmpt_4lsE',
    appId: '1:802294275670:ios:fe48b597ba46c15ae5a5f7',
    messagingSenderId: '802294275670',
    projectId: 'notz-6b2b2',
    storageBucket: 'notz-6b2b2.appspot.com',
    iosBundleId: 'com.example.notz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoEhABLIbuDZyk8M5EM_ITqsNHbJj18os',
    appId: '1:802294275670:web:a9d82a98d77be9c9e5a5f7',
    messagingSenderId: '802294275670',
    projectId: 'notz-6b2b2',
    authDomain: 'notz-6b2b2.firebaseapp.com',
    storageBucket: 'notz-6b2b2.appspot.com',
    measurementId: 'G-EP79CGEHTJ',
  );
}
